[project]
name = 'clarity-commit-reveal'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.bitcoin-helper]
path = 'contracts/bitcoin-helper.clar'
clarity_version = 2
epoch = 2.1

[contracts.clarity-bitcoin-helper]
path = 'contracts/external/clarity-bitcoin-helper.clar'
clarity_version = 2
epoch = 2.1

[contracts.clarity-bitcoin-v5]
path = 'contracts/external/clarity-bitcoin-v5.clar'
clarity_version = 2
epoch = 2.1

[contracts.commit-submission]
path = 'contracts/commit-submission.clar'
clarity_version = 2
epoch = 2.1

[contracts.reveal-submission]
path = 'contracts/reveal-submission.clar'
clarity_version = 2
epoch = 2.1

[contracts.transaction-storage]
path = 'contracts/transaction-storage.clar'
clarity_version = 2
epoch = 2.1

[contracts.witness-helper]
path = 'contracts/witness-helper.clar'
clarity_version = 2
epoch = 2.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
